# Generated by Django 4.2.3 on 2024-12-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='qtd_vacinas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.CharField(max_length=30),
        ),
    ]
