# Generated by Django 4.2.3 on 2024-11-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sala_numero", models.IntegerField()),
                ("hora_inicio", models.DateTimeField()),
                ("hora_fim", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
            },
        ),
    ]
